# Reference
# https://docs.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates#about-the-dependabotyml-file
version: 1

updates:
  - package-ecosystem: npm
    directory: "/frontend"
    schedule:
      interval: weekly
      time: "11:00"
      timezone: Asia/Seoul
    open-pull-requests-limit: 10
    target-branch: main
    reviewers:
      - "classtinginc/ppark2ya"
    labels:
      - "Dependencies"
      - "Backend"
