nodeLinker: node-modules
yarnPath: .yarn/releases/yarn-3.0.2.cjs
# https://stackoverflow.com/questions/61738819/installing-private-package-from-github-package-registry-using-yarn-fails-with-no
npmScopes:
  "nolmungshemung":
    npmAlwaysAuth: true
    npmRegistryServer: "https://npm.pkg.github.com"
		npmAuthToken: ${GITHUB_ACCESS_TOKEN}
