import type { NextPage } from 'next';
import Head from 'next/head';
import { useMainContents } from '~/data/services/services.hooks';

const Home: NextPage = function () {
  const { data: mainContents } = useMainContents('test');

  console.log(mainContents);
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
  );
};

/**
 * @see https://react-query.tanstack.com/guides/ssr
 */
// export async function getServerSideProps() {
//   const queryClient = new QueryClient();

//   await queryClient.prefetchInfiniteQuery('todos', () => getTodos(), {
//     staleTime: 10000,
//   });

//   /**
//    * @see https://github.com/tannerlinsley/react-query/issues/1458
//    */
//   const dehydratedState = JSON.parse(JSON.stringify(dehydrate(queryClient)));

//   return {
//     props: {
//       dehydratedState,
//     },
//   };
// }

export default Home;
