import type { NextPage } from 'next';
import Head from 'next/head';
import { useMainContents } from '~/data/services/services.hooks';

/* TO-DO : 로그인 여부 체크해서 로그인했을경우 메인페이지 아니면 로그인 페이지 띄우기
 * 기획 상 로그인 여부와 상관없이 메인 페이지 접근 가능할경우 여기를 메인으로 써야함
 */

const Home: NextPage = function () {
  const { data: mainContents, error } = useMainContents('invalid');

  console.log(mainContents);
  console.log(error?.response?.data);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
  );
};

/**
 * @see https://react-query.tanstack.com/guides/ssr
 */
// export async function getServerSideProps() {
//   const queryClient = new QueryClient();

//   await queryClient.prefetchInfiniteQuery('todos', () => getTodos(), {
//     staleTime: 10000,
//   });

//   /**
//    * @see https://github.com/tannerlinsley/react-query/issues/1458
//    */
//   const dehydratedState = JSON.parse(JSON.stringify(dehydrate(queryClient)));

//   return {
//     props: {
//       dehydratedState,
//     },
//   };
// }

export default Home;
