on:
  pull_request:
    branches:
      - main
    paths:
      - "backend/**"
      - ".github/workflows/apptest.yaml"
defaults:
  run:
    working-directory: backend
jobs:
  deploy:
    name: App Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./backend/requirements.txt
      - name: Test
        run: |
          pytest -v