name: WritingHub Web Dev

on:
  push:
    branches-ignore:
      - main
    paths:
      - "web/**"
      - ".github/workflows/web-dev.yml"

env:
  AWS_DEFAULT_REGION: us-east-1
  AWS_ACCESS_KEY_ID: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
  NODE_OPTIONS: --max_old_space_size=4096
  CF_DISTRIBUTION_ID: ${{ secrets.WEB_DEV_CF_DISTRIBUTION_ID }}

jobs:
  install-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install dependencies
        run: yarn install --immutable --immutable-cache

  lint:
    runs-on: ubuntu-latest
    needs: [install-dependencies]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install dependencies
        run: yarn install --immutable --immutable-cache

      - name: Lint
        run: yarn lint

  unit-testing:
    runs-on: ubuntu-latest
    needs: [install-dependencies]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install dependencies
        run: yarn install --immutable --immutable-cache

      - name: Unit testing
        run: |
          yarn test \
            --ci \
            --runInBand \
            --coverage \
            --watchAll=false \
            --passWithNoTests

  deploy:
    runs-on: ubuntu-latest
    needs: [install-dependencies]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: canastro/copy-file-action@master
        with:
          source: "serverless-dev.yml"
          target: "serverless.yml"

      - name: Setup node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install dependencies
        run: yarn install --immutable --immutable-cache

      - name: Export env from aws ssm
        uses: nolmungshemung/chamber-action@main
        with:
          args: export --format dotenv --output-file .env dev/writinghub-web

      - name: Serverless AWS authentication
        run: yarn serverless --component=serverless-next config credentials --provider aws --key ${{ secrets.DEV_AWS_ACCESS_KEY_ID }} --secret ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}

      - name: Download `.serverless` state from S3
        run: aws s3 sync s3://sls-norsh-dev-us-east-1/serverless/writinghub-web/dev/.serverless .serverless --delete

      - name: Deploy to AWS
        run: yarn serverless

      - name: Upload `.serverless` state to S3
        run: aws s3 sync .serverless s3://sls-norsh-dev-us-east-1/serverless/writinghub-web/dev/.serverless --delete
