name: WritingHub Web Dev

on:
  push:
    branches-ignore:
      - main
    paths:
      - "web/**"
      - ".github/workflows/web-dev.yml"

env:
  AWS_DEFAULT_REGION: us-east-1
  AWS_ACCESS_KEY_ID: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
  NODE_OPTIONS: --max_old_space_size=4096
  CF_DISTRIBUTION_ID: ${{ secrets.WEB_DEV_CF_DISTRIBUTION_ID }}

defaults:
  run:
    working-directory: web

jobs:
  install-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install dependencies
        run: yarn install --immutable --immutable-cache

  lint:
    runs-on: ubuntu-latest
    needs: [install-dependencies]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install dependencies
        run: yarn install --immutable --immutable-cache

      - name: Lint
        run: yarn lint

  unit-testing:
    runs-on: ubuntu-latest
    needs: [install-dependencies]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install dependencies
        run: yarn install --immutable --immutable-cache

      - name: Unit testing
        run: |
          yarn test \
            --ci \
            --runInBand \
            --coverage \
            --watchAll=false \
            --passWithNoTests

  deploy:
    runs-on: ubuntu-latest
    needs: [install-dependencies]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install dependencies
        run: yarn install --immutable --immutable-cache

      - name: Export env from aws ssm
        uses: nolmungshemung/chamber-action@main
        with:
          args: export --format dotenv --output-file .env dev/writinghub-web

      - name: Deploy to AWS
        working-directory: ./web
        run: yarn deploy
